### PR TITLE
Remove unsupported architectures

### PR DESCRIPTION
**Pull request by mikenye**
Remove architectures not supported by docker, causing action to fail.

### CODE REVIEW

**Review by willfarrell — APPROVED** [review]

**Comment by mikenye** [comment]
Apologies that my previous PR (#50) caused the action to fail. I wrongly assumed it would only build for supported platforms. I’ve tested this one.

**Comment by willfarrell** [comment]
All good, it happens. Thanks for submitting a fix.

**Comment by mikenye** [comment]
No problems! Gotta fix what you break. :-)

**Comment by mikenye** [comment]
FYI image runs fine on arm64 and arm/v7!

**Pull request merged**
