### PR TITLE
Added delayed restart mode

### PR DESCRIPTION
**Pull request by adbrvn**
Container will be restarted at second check. In may be useful for containers with selfhealing

### CODE REVIEW

**Comment by hasnat** [comment]
I would go against this change, feels like health check of your container should be adjusted.

**Comment by adbrvn** [comment]
May be it sounds like hack, but in my case i should to double check before restart service.

**Comment by hasnat** [comment]
Can you double check within your healthcheck cmd ?
e.g. adjusting `interval` + `retries` count would achieve stricter healtcheck for your service

**Comment by adbrvn** [comment]
Hm, you'll right. I forgot about retries parameter. Thanks.

**Pull request closed without merging**
